/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.interfaz;

import com.sucursales.AlmacenRed;
import com.sucursales.Grafo;
import com.sucursales.Lista;
import com.sucursales.RedDeTransporte;
import com.sucursales.VisualizadorGrafo;
import javax.swing.JOptionPane;

/**
 *
 * @author xc2do
 */
public class AgregarLinea extends javax.swing.JFrame {

    /**
     * Creates new form AgregarLinea
     */
    public AgregarLinea() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nombreLineaTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        estacionesTextArea = new javax.swing.JTextArea();
        MenuButton = new javax.swing.JToggleButton();
        AgregarLinea = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreLineaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreLineaTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(nombreLineaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 120, 30));

        estacionesTextArea.setColumns(20);
        estacionesTextArea.setRows(5);
        jScrollPane1.setViewportView(estacionesTextArea);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 250, 230));

        MenuButton.setText("Menu");
        MenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuButtonActionPerformed(evt);
            }
        });
        jPanel1.add(MenuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 120, 30));

        AgregarLinea.setText("agregar");
        AgregarLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarLineaActionPerformed(evt);
            }
        });
        jPanel1.add(AgregarLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 120, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuButtonActionPerformed
        Menu menu = new Menu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuButtonActionPerformed

    private void nombreLineaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreLineaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreLineaTextFieldActionPerformed

    private void AgregarLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarLineaActionPerformed
        String nombreLinea = nombreLineaTextField.getText(); // Obtener el nombre de la línea
        String[] estacionesLista = estacionesTextArea.getText().split(","); // Obtener la secuencia de estaciones
        Lista<String> estaciones = new Lista<>();
        for (String estacion : estacionesLista) {
            estaciones.agregar(estacion.trim());
        }
        RedDeTransporte red = AlmacenRed.getRedDeTransporte(); // Obtener la red de transporte
        red.agregarLineaNueva(nombreLinea, estaciones); // Agregar la nueva línea a la red
        JOptionPane.showMessageDialog(this, "Nueva línea " + nombreLinea + " agregada.", "Línea Agregada", JOptionPane.INFORMATION_MESSAGE);

        // Actualizar el grafo
        Grafo grafo = red.getGrafo();
        VisualizadorGrafo.visualizar(grafo);
    }//GEN-LAST:event_AgregarLineaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarLinea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarLinea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarLinea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarLinea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarLinea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarLinea;
    private javax.swing.JToggleButton MenuButton;
    private javax.swing.JTextArea estacionesTextArea;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombreLineaTextField;
    // End of variables declaration//GEN-END:variables
}
