/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.interfaz;

import com.sucursales.AlmacenRed;
import com.sucursales.Grafo;
import com.sucursales.RedDeTransporte;
import com.sucursales.VisualizadorGrafo;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author xc2do
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CargarButton = new javax.swing.JLabel();
        Salir = new javax.swing.JLabel();
        AgregarLinea = new javax.swing.JLabel();
        ColocarSucursal = new javax.swing.JLabel();
        EstablecerParadas = new javax.swing.JLabel();
        MostrarGrafo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CargarButton.setFont(new java.awt.Font("Roboto Medium", 0, 36)); // NOI18N
        CargarButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CargarButton.setText("CARGAR RED");
        CargarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CargarButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CargarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CargarButtonMouseClicked(evt);
            }
        });
        jPanel1.add(CargarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 220, 60));

        Salir.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        Salir.setForeground(new java.awt.Color(255, 255, 255));
        Salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Salir.setText("SALIR ");
        Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SalirMouseEntered(evt);
            }
        });
        jPanel1.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 396, 350, 90));

        AgregarLinea.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        AgregarLinea.setForeground(new java.awt.Color(255, 255, 255));
        AgregarLinea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AgregarLinea.setText("Agregar Linea");
        AgregarLinea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AgregarLinea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarLineaMouseClicked(evt);
            }
        });
        jPanel1.add(AgregarLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, 330, 60));

        ColocarSucursal.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        ColocarSucursal.setForeground(new java.awt.Color(255, 255, 255));
        ColocarSucursal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ColocarSucursal.setText("Colocar Sucursal");
        ColocarSucursal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ColocarSucursal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ColocarSucursalMouseClicked(evt);
            }
        });
        jPanel1.add(ColocarSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 330, 60));

        EstablecerParadas.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        EstablecerParadas.setForeground(new java.awt.Color(255, 255, 255));
        EstablecerParadas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EstablecerParadas.setText("Establecer Rango");
        EstablecerParadas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EstablecerParadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EstablecerParadasMouseClicked(evt);
            }
        });
        jPanel1.add(EstablecerParadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 330, 60));

        MostrarGrafo.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        MostrarGrafo.setForeground(new java.awt.Color(255, 255, 255));
        MostrarGrafo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MostrarGrafo.setText("Mostrar Grafo");
        MostrarGrafo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MostrarGrafo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MostrarGrafoMouseClicked(evt);
            }
        });
        jPanel1.add(MostrarGrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 330, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/MenuCompleto.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MostrarGrafoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MostrarGrafoMouseClicked
        RedDeTransporte red = AlmacenRed.getRedDeTransporte();

        if (red != null) {
            System.out.println("Red de transporte recuperada:");
            System.out.println(red);

            Grafo grafo = red.getGrafo(); //usamos el grafo directamente desde AlmacenRed

            VisualizadorGrafo.visualizar(grafo);
        } else {
            System.out.println("No se ha cargado ninguna red de transporte.");
            JOptionPane.showMessageDialog(this, "No se ha cargado ninguna red de transporte", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_MostrarGrafoMouseClicked

    private void EstablecerParadasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EstablecerParadasMouseClicked
        EstablecerCobertura establecerCobertura = new EstablecerCobertura();
        establecerCobertura.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EstablecerParadasMouseClicked

    private void ColocarSucursalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ColocarSucursalMouseClicked
        RedDeTransporte red = AlmacenRed.getRedDeTransporte();
        if (red != null) {
            System.out.println("Red de transporte recuperada:");
            ColocarSucursal colocarSucursal = new ColocarSucursal();
            colocarSucursal.setVisible(true);
            this.dispose();
        } else {
            System.out.println("No se ha cargado ninguna red de transporte.");
            JOptionPane.showMessageDialog(this, "No se ha cargado ninguna red de transporte", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ColocarSucursalMouseClicked

    private void CargarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CargarButtonMouseClicked
        BuscarArchivo cargarArchivo = new BuscarArchivo();
        cargarArchivo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CargarButtonMouseClicked

    private void AgregarLineaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarLineaMouseClicked
        AgregarLinea agregarLinea = new AgregarLinea();
        agregarLinea.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AgregarLineaMouseClicked

    private void SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_SalirMouseClicked

    private void SalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseEntered
        //nada lo intente
    }//GEN-LAST:event_SalirMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgregarLinea;
    private javax.swing.JLabel CargarButton;
    private javax.swing.JLabel ColocarSucursal;
    private javax.swing.JLabel EstablecerParadas;
    private javax.swing.JLabel MostrarGrafo;
    private javax.swing.JLabel Salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
