/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.interfaz;

import com.sucursales.AlmacenRed;
import com.sucursales.Grafo;
import com.sucursales.RedDeTransporte;
import com.sucursales.VisualizadorGrafo;
import javax.swing.JOptionPane;

/**
 *
 * @author xc2do
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        DFS = new javax.swing.JButton();
        bg = new javax.swing.JPanel();
        MostrarGrafo = new javax.swing.JLabel();
        EstablecerParadas = new javax.swing.JLabel();
        CargarButton = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        jButton2.setText("jButton2");

        jButton1.setText("jButton1");

        jButton3.setText("jButton3");

        jButton4.setText("jButton4");

        DFS.setText("DFS");
        DFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DFSActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MostrarGrafo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MostrarGrafoMouseClicked(evt);
            }
        });
        bg.add(MostrarGrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 320, 40));

        EstablecerParadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EstablecerParadasMouseClicked(evt);
            }
        });
        bg.add(EstablecerParadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 320, 40));

        CargarButton.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        CargarButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CargarButton.setText("CARGAR RED");
        CargarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CargarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CargarButtonMouseClicked(evt);
            }
        });
        bg.add(CargarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 240, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/MenuDef.png"))); // NOI18N
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 800, 500));

        jButton5.setText("jButton5");
        bg.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 440, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CargarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CargarButtonMouseClicked
        BuscarArchivo cargarArchivo = new BuscarArchivo();
        cargarArchivo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CargarButtonMouseClicked

    private void MostrarGrafoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MostrarGrafoMouseClicked
        RedDeTransporte red = AlmacenRed.getRedDeTransporte();
        if (red != null) {
            System.out.println("Red de transporte recuperada:");
            System.out.println(red);

            Grafo grafo = Grafo.construirGrafo(red);
            VisualizadorGrafo.visualizar(grafo);
        } else {
            System.out.println("No se ha cargado ninguna red de transporte.");
            JOptionPane.showMessageDialog(this, "No se ha cargado ninguna red de transporte", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_MostrarGrafoMouseClicked

    private void EstablecerParadasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EstablecerParadasMouseClicked
        EstablecerCobertura establecerCobertura = new EstablecerCobertura();
        establecerCobertura.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EstablecerParadasMouseClicked

    private void DFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DFSActionPerformed
        public String[] coberturaDFS(String sucursal) {
        Pila pila = new Pila();
        boolean[] visitado = new boolean[numParadas];
        String[] resultado = new String[numParadas];
        int coberturaCount = 0;

        int indice = buscarIndice(sucursal);
        if (indice == -1) return resultado;

        pila.apilar(paradaPorIndice(indice));
        visitado[indice] = true;
        int nivel = 0;

        while (!pila.estaVacia() && nivel <= t) {
            String actual = pila.desapilar();
            resultado[coberturaCount++] = actual;
            int actualIndice = buscarIndice(actual);
            for (int j = 0; j < numParadas; j++) {
                if (conexiones[actualIndice][j] == 1 && !visitado[j]) {
                    pila.apilar(paradaPorIndice(j));
                    visitado[j] = true;
                }
            }
            nivel++;
        }
        return resultado;
    }
    }//GEN-LAST:event_DFSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CargarButton;
    private javax.swing.JButton DFS;
    private javax.swing.JLabel EstablecerParadas;
    private javax.swing.JLabel MostrarGrafo;
    private javax.swing.JPanel bg;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
